import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../data/models/export_data_model.dart';

/// Generates a doctor-ready A4 PDF report from [ExportDataModel].
///
/// Sections:
///   1. Header with date range
///   2. Cycle Summary (averages, variation, total periods)
///   3. Month-by-Month breakdown table
///   4. Symptom Frequency summary table
///   5. Pattern highlights (cycle regularity)
///
/// Designed to run inside [Isolate.run()] -- no Flutter/UI dependencies.
/// Uses [MultiPage] for page-by-page streaming (Karla Note 5).
class PdfExporter {
  const PdfExporter();

  // Brand colours replicated from AppColors (no Flutter import needed here)
  static const _primary = PdfColor.fromInt(0xFF2D6A7A);
  static const _secondary = PdfColor.fromInt(0xFFD4896A);
  static const _textPrimary = PdfColor.fromInt(0xFF2D2D2D);
  static const _textSecondary = PdfColor.fromInt(0xFF6B6B6B);
  static const _surface = PdfColor.fromInt(0xFFFFFFFF);
  static const _borderColor = PdfColor.fromInt(0xFFE0E0E0);

  /// Converts [data] into an A4 PDF byte array.
  ///
  /// Returns raw PDF bytes ready to be written to a .pdf file.
  /// The caller ([ExportService]) wraps this in [Isolate.run()].
  Future<Uint8List> generate(ExportDataModel data) async {
    final doc = pw.Document(
      title: 'Cara Cycle Report',
      author: 'Cara',
      creator: 'Cara - Privacy-First Period Tracker',
    );

    final dateFormat = DateFormat('MMM d, yyyy');
    final rangeLabelStart = data.startDate != null
        ? dateFormat.format(data.startDate!)
        : 'All time';
    final rangeLabelEnd = dateFormat.format(data.endDate);
    final rangeLabel = '$rangeLabelStart - $rangeLabelEnd';

    final symptomCounts = <String, int>{};
    for (final day in data.dailyData) {
      for (final entry in day.symptomEntries) {
        final name = entry.symptom?.name ?? 'Unknown';
        symptomCounts[name] = (symptomCounts[name] ?? 0) + 1;
      }
    }
    final sortedSymptoms = symptomCounts.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    final monthBuckets = _buildMonthBuckets(data);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        header: (context) => _buildHeader(context, rangeLabel),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          pw.SizedBox(height: 8),
          _sectionTitle('Cycle Summary'),
          pw.SizedBox(height: 6),
          _cycleSummaryTable(data),
          pw.SizedBox(height: 20),
          _sectionTitle('Month-by-Month Breakdown'),
          pw.SizedBox(height: 6),
          _monthTable(monthBuckets),
          pw.SizedBox(height: 20),
          _sectionTitle('Symptom Frequency'),
          pw.SizedBox(height: 6),
          if (sortedSymptoms.isEmpty)
            _emptyState('No symptoms logged in this period.')
          else
            _symptomTable(sortedSymptoms),
          pw.SizedBox(height: 20),
          _sectionTitle('Pattern Highlights'),
          pw.SizedBox(height: 6),
          _patternHighlights(data),
        ],
      ),
    );

    return doc.save();
  }

  pw.Widget _buildHeader(pw.Context context, String rangeLabel) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Cycle Report',
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
                color: _primary,
              ),
            ),
            pw.Text(
              rangeLabel,
              style: pw.TextStyle(fontSize: 10, color: _textSecondary),
            ),
          ],
        ),
        pw.SizedBox(height: 4),
        pw.Divider(color: _primary, thickness: 1.5),
        pw.SizedBox(height: 4),
      ],
    );
  }

  pw.Widget _buildFooter(pw.Context context) {
    return pw.Column(
      children: [
        pw.Divider(color: _borderColor, thickness: 0.5),
        pw.SizedBox(height: 2),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by Cara - your data never leaves your device.',
              style: pw.TextStyle(fontSize: 8, color: _textSecondary),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: pw.TextStyle(fontSize: 8, color: _textSecondary),
            ),
          ],
        ),
      ],
    );
  }

  pw.Widget _sectionTitle(String title) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 4),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: _secondary, width: 1),
        ),
      ),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize: 13,
          fontWeight: pw.FontWeight.bold,
          color: _primary,
        ),
      ),
    );
  }

  pw.Widget _emptyState(String message) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 8),
      child: pw.Text(
        message,
        style: pw.TextStyle(fontSize: 10, color: _textSecondary),
      ),
    );
  }

  pw.Widget _cycleSummaryTable(ExportDataModel data) {
    final stats = data.stats;
    final totalPeriodDays =
        data.dailyData.where((d) => d.periodLog != null).length;

    final avgCycleStr = stats != null
        ? '${stats.avgCycleLength.toStringAsFixed(1)} days'
        : '--';
    final variationStr = stats != null
        ? '${stats.minCycleLength}-${stats.maxCycleLength} days'
        : '--';
    final avgPeriodStr = stats != null
        ? '${stats.avgPeriodLength.toStringAsFixed(1)} days'
        : '--';
    final totalCyclesStr =
        stats != null ? stats.totalCycles.toString() : '--';
    final regularityStr = stats == null
        ? '--'
        : (stats.isIrregular ? 'Irregular (>5 day variance)' : 'Regular');

    final rows = <List<String>>[
      ['Average Cycle Length', avgCycleStr],
      ['Cycle Variation', variationStr],
      ['Average Period Length', avgPeriodStr],
      ['Total Cycles Recorded', totalCyclesStr],
      ['Total Period Days in Range', totalPeriodDays.toString()],
      ['Cycle Regularity', regularityStr],
    ];

    return pw.Table(
      border: pw.TableBorder.all(color: _borderColor, width: 0.5),
      columnWidths: const {
        0: pw.FlexColumnWidth(2),
        1: pw.FlexColumnWidth(1.5),
      },
      children: rows.map((row) {
        return pw.TableRow(
          children: [
            _tableCell(row[0], isLabel: true),
            _tableCell(row[1]),
          ],
        );
      }).toList(),
    );
  }

  List<_MonthBucket> _buildMonthBuckets(ExportDataModel data) {
    final buckets = <String, _MonthBucket>{};
    final monthFormat = DateFormat('MMM yyyy');

    for (final day in data.dailyData) {
      // Build YYYY-MM key using string interpolation without nested quotes
      final month = day.date.month.toString().padLeft(2, '0');
      final key = '${day.date.year}-$month';
      final label = monthFormat.format(day.date);
      buckets.putIfAbsent(key, () => _MonthBucket(label: label));
      final bucket = buckets[key]!;
      if (day.periodLog != null) bucket.periodDays++;
      if (day.symptomEntries.isNotEmpty) bucket.symptomDays++;
      bucket.totalDays++;
    }

    final sorted = buckets.entries.toList()
      ..sort((a, b) => a.key.compareTo(b.key));
    return sorted.map((e) => e.value).toList();
  }

  pw.Widget _monthTable(List<_MonthBucket> buckets) {
    if (buckets.isEmpty) {
      return _emptyState('No data in this date range.');
    }

    final headerRow = pw.TableRow(
      decoration: const pw.BoxDecoration(color: _primary),
      children: [
        _tableCell('Month', isHeader: true),
        _tableCell('Period Days', isHeader: true),
        _tableCell('Symptom Days', isHeader: true),
        _tableCell('Days Logged', isHeader: true),
      ],
    );

    final dataRows = buckets.map((b) {
      return pw.TableRow(
        children: [
          _tableCell(b.label),
          _tableCell(b.periodDays.toString()),
          _tableCell(b.symptomDays.toString()),
          _tableCell(b.totalDays.toString()),
        ],
      );
    }).toList();

    return pw.Table(
      border: pw.TableBorder.all(color: _borderColor, width: 0.5),
      columnWidths: const {
        0: pw.FlexColumnWidth(2),
        1: pw.FlexColumnWidth(1),
        2: pw.FlexColumnWidth(1),
        3: pw.FlexColumnWidth(1),
      },
      children: [headerRow, ...dataRows],
    );
  }


  pw.Widget _symptomTable(List<MapEntry<String, int>> symptoms) {
    final top = symptoms.take(15).toList();
    final maxCount = top.first.value;

    final headerRow = pw.TableRow(
      decoration: const pw.BoxDecoration(color: _primary),
      children: [
        _tableCell('Symptom', isHeader: true),
        _tableCell('Days Logged', isHeader: true),
        _tableCell('Frequency', isHeader: true),
      ],
    );

    final dataRows = top.map((entry) {
      final barFraction = maxCount > 0 ? entry.value / maxCount : 0.0;
      return pw.TableRow(
        children: [
          _tableCell(_capitalize(entry.key)),
          _tableCell(entry.value.toString()),
          pw.Padding(
            padding: const pw.EdgeInsets.all(4),
            child: pw.Row(
              children: [
                pw.Flexible(
                  flex: (barFraction * 100).round(),
                  child: pw.Container(
                    height: 10,
                    decoration: pw.BoxDecoration(
                      color: _secondary,
                      borderRadius: pw.BorderRadius.circular(2),
                    ),
                  ),
                ),
                if (barFraction < 1.0)
                  pw.Flexible(
                    flex: ((1.0 - barFraction) * 100).round(),
                    child: pw.SizedBox(height: 10),
                  ),
              ],
            ),
          ),
        ],
      );
    }).toList();

    return pw.Table(
      border: pw.TableBorder.all(color: _borderColor, width: 0.5),
      columnWidths: const {
        0: pw.FlexColumnWidth(2),
        1: pw.FlexColumnWidth(1),
        2: pw.FlexColumnWidth(3),
      },
      children: [headerRow, ...dataRows],
    );
  }

  pw.Widget _patternHighlights(ExportDataModel data) {
    final highlights = <String>[];
    final stats = data.stats;

    if (stats != null) {
      if (stats.isIrregular) {
        highlights.add(
          'Your cycles show high variability '
          '(${stats.minCycleLength}-${stats.maxCycleLength} days). '
          'This may be worth discussing with your healthcare provider.',
        );
      } else {
        highlights.add(
          'Your cycles are regular, ranging between '
          '${stats.minCycleLength} and ${stats.maxCycleLength} days '
          'with an average of ${stats.avgCycleLength.toStringAsFixed(1)} days.',
        );
      }

      if (stats.totalCycles >= 3) {
        highlights.add(
          'Based on ${stats.totalCycles} recorded cycles, '
          'Cara can provide period predictions.',
        );
      } else {
        final remaining = 3 - stats.totalCycles;
        final plural = remaining == 1 ? '' : 's';
        highlights.add('Log $remaining more complete cycle$plural to enable period predictions.');
      }
    }

    final symptomCounts = <String, int>{};
    for (final day in data.dailyData) {
      for (final entry in day.symptomEntries) {
        final name = entry.symptom?.name ?? 'Unknown';
        symptomCounts[name] = (symptomCounts[name] ?? 0) + 1;
      }
    }
    if (symptomCounts.isNotEmpty) {
      final topEntry = (symptomCounts.entries.toList()
            ..sort((a, b) => b.value.compareTo(a.value)))
          .first;
      final plural = topEntry.value == 1 ? '' : 's';
      highlights.add(
        'Most frequently logged symptom: "${_capitalize(topEntry.key)}" '
        '(${topEntry.value} day$plural).',
      );
    }

    if (highlights.isEmpty) {
      return _emptyState('Not enough data for pattern highlights. Keep logging!');
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: highlights.map((h) {
        return pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 6),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                width: 6,
                height: 6,
                margin: const pw.EdgeInsets.only(top: 3, right: 8),
                decoration: const pw.BoxDecoration(
                  color: _secondary,
                  shape: pw.BoxShape.circle,
                ),
              ),
              pw.Expanded(
                child: pw.Text(
                  h,
                  style: pw.TextStyle(fontSize: 10, color: _textPrimary),
                ),
              ),
            ],
          ),
        );
      }).toList(),
    );
  }


  pw.Widget _tableCell(
    String text, {
    bool isLabel = false,
    bool isHeader = false,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: (isLabel || isHeader)
              ? pw.FontWeight.bold
              : pw.FontWeight.normal,
          color: isHeader ? _surface : _textPrimary,
        ),
      ),
    );
  }

  String _capitalize(String s) {
    if (s.isEmpty) return s;
    return '${s[0].toUpperCase()}${s.substring(1)}';
  }
}

/// Internal helper for month-by-month data aggregation.
class _MonthBucket {
  _MonthBucket({required this.label});
  final String label;
  int periodDays = 0;
  int symptomDays = 0;
  int totalDays = 0;
}
